# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish

on:
  release:
    types: [created]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: make dev

  coverage:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    needs: install
    steps:
    - name: Test
      run: make test
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install coveralls
        coveralls

  publish:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Build and publish
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        make package
        twine upload dist/*
